export const languages = {
	german: {
		'Manage Campaigns': 'Kampagnen verwalten',
		'Upcoming Campaigns': 'Kommende Kampagnen',
		'Live Campaigns': 'Live-Kampagnen',
		'Past Campaigns': 'Vergangene Kampagnen',
		DATE: 'DATUM',
		CAMPAIGN: 'KAMPAGNE',
		VIEW: 'AUSSICHT',
		ACTIONS: 'AKTIONEN',
		'View Pricing': 'Preise anzeigen',
		CSV: 'CSV',
		Report: 'Bericht',
		'Schedule Again': 'Planen Sie erneut',
		Jan: 'Januar',
		Feb: 'Februar',
		March: 'März',
		April: 'April',
		May: 'Kann',
		Jun: 'Juni',
		Jul: 'Juli',
		Aug: 'Aug',
		Sep: 'Sep',
		Oct: 'Oktober',
		Nov: 'Nov',
		Dec: 'Dezember',
		'ends on': 'endet am',
		'days ago': 'Vor Tagen',
		'days ahead': 'Tage voraus',
		Pricing: 'Preisgestaltung',
		'1 Week - 1 Month': '1 Woche - 1 Monat',
		'6 Months': '6 Monate',
		'1 Year': '1 Jahr',
		Close: 'Schließen',
	},
	english: {
		'Manage Campaigns': 'Manage Campaigns',
		'Upcoming Campaigns': 'Upcoming Campaigns',
		'Live Campaigns': 'Live Campaigns',
		'Past Campaigns': 'Past Campaigns',
		DATE: 'DATE',
		CAMPAIGN: 'CAMPAIGN',
		VIEW: 'VIEW',
		ACTIONS: 'ACTIONS',
		'View Pricing': 'View Pricing',
		CSV: 'CSV',
		Report: 'Report',
		'Schedule Again': 'Schedule Again',
		Jan: 'Jan',
		Feb: 'Feb',
		March: 'March',
		April: 'April',
		May: 'May',
		Jun: 'Jun',
		Jul: 'Jul',
		Aug: 'Aug',
		Sep: 'Sep',
		Oct: 'Oct',
		Nov: 'Nov',
		Dec: 'Dec',
		'ends on': 'ends on',
		'days ago': 'days ago',
		'days ahead': 'days ahead',
		Pricing: 'Pricing',
		'1 Week - 1 Month': '1 Week - 1 Month',
		'6 Months': '6 Months',
		'1 Year': '1 Year',
		Close: 'Close',
	},
};
